[package]
name = "hash-to-float"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
xxhash-rust = { version = "0.8.6", features = ["xxh3", "xxh32"] }
